services:
  broker-2:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: broker-2
    restart: always
    env_file:
      # - ./env/common.env
      - ./env/deploy.env
    networks:
      - integration-network
    ports:
      - 9092:9092
      - 19092:19092
      - 29092:29092
      - 9200:9200
    tty: true
    environment:
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@${CONTROLLER_1_IP}:39092,2@${CONTROLLER_2_IP}:39092"
      # KAFKA_LISTENERS: INTERNAL://broker-2:19092,DOCKER_HOST://broker-2:9092,EXTERNAL://broker-2:29092
      # KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-2:19092,DOCKER_HOST://localhost:9092,EXTERNAL://${BROKER_2_IP}:29092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,DOCKER_HOST:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,DOCKER_HOST://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${BROKER_2_IP}:19092,DOCKER_HOST://localhost:9092,EXTERNAL://${BROKER_2_IP}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,DOCKER_HOST:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-${JMX_AGENT_VERSION}.jar=9200:/usr/share/jmx_exporter/kafka-controller.yml 
    volumes:
      - broker_2_data:/var/lib/kafka/data
      - ./plugins/jmx-exporter:/usr/share/jmx_exporter/

networks:
  integration-network:
    name: integration-network
    driver: bridge

volumes:
  broker_2_data:
