ALTER SESSION SET CURRENT_SCHEMA = LIM_W1_HL;

CREATE TABLE "LIM_W1_HL"."KUND" (
	"KUND_CUSTOMER_NO_" NUMBER(6, 0) NOT NULL ENABLE,
	"KUND_OLD_CUSTOMER_NO_" NUMBER(5, 0) NOT NULL ENABLE,
	"KUND_NAME_1" VARCHAR2(100 CHAR) NOT NULL ENABLE,
	"KUND_NAME_2" VARCHAR2(100 CHAR) NOT NULL ENABLE,
	"KUND_NAME_3" VARCHAR2(100 CHAR) NOT NULL ENABLE,
	"KUND_STREET_1" VARCHAR2(100 CHAR) NOT NULL ENABLE,
	"KUND_STREET_2" VARCHAR2(100 CHAR) NOT NULL ENABLE,
	"KUND_ZIP_CODE_P_O_BOX" VARCHAR2(9 CHAR) NOT NULL ENABLE,
	"KUND_POST_OFFICE_BOX" VARCHAR2(8 CHAR) NOT NULL ENABLE,
	"KUND_ZIP_CODE" VARCHAR2(9 CHAR) NOT NULL ENABLE,
	"KUND_CITY" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"KUND_COUNTRY" VARCHAR2(8 CHAR) NOT NULL ENABLE,
	"KUND_STATE_PROVINCE" VARCHAR2(11 CHAR) NOT NULL ENABLE,
	"KUND_VAT_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"KUND_TELEPHONE" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"KUND_FAX" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"KUND_E_MAIL" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"KUND_SITA_CODE" VARCHAR2(7 CHAR) NOT NULL ENABLE,
	"KUND_2_LETTER_CODE" VARCHAR2(2 CHAR) NOT NULL ENABLE,
	"KUND_3_LETTER_CODE" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"KUND_PREFIX" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"KUND_CASS_BILLING_CC" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_IATA_CA_NUMERICAL_CODE" NUMBER(7, 0) NOT NULL ENABLE,
	"KUND_IATA_CASS_ADDRESS" NUMBER(4, 0) NOT NULL ENABLE,
	"KUND_ABBREVIATED_NAME" VARCHAR2(17 CHAR) NOT NULL ENABLE,
	"KUND_VAT" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_BLOCKED_DISABLED" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_CASH_PAYER" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_CUSTOMS_FEE_FULL" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_LIABLILITY_CODE" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"KUND_CUSTOMER_TYPE_CODE" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"KUND_PHYS_HANDLING" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"KUND_LOAD_SPLIT" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_OPS_THROUGH" VARCHAR2(17 CHAR) NOT NULL ENABLE,
	"KUND_GSA" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"KUND_GSA_CONTACT_PERSON" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"KUND_TELEPHONE1" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"KUND_LAST_INV_MOVEMENT" NUMBER(10, 0) NOT NULL ENABLE,
	"KUND_LAST_MODIFIED_ON" NUMBER(10, 0) NOT NULL ENABLE,
	"KUND_LAST_MODIFIED_AT" RAW(6) NOT NULL ENABLE,
	"KUND_MODIFIED_BY" VARCHAR2(17 CHAR) NOT NULL ENABLE,
	"KUND_CUSTOMS_TRANSFER" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_CUSTOMS_CALCULATION" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_CUSTOMS_NAME" VARCHAR2(17 CHAR) NOT NULL ENABLE,
	"KUND_LVG" VARCHAR2(5 CHAR) NOT NULL ENABLE,
	"KUND_CUSTOMS_NUMBER" NUMBER(7, 0) NOT NULL ENABLE,
	"KUND_EG_CARRIER" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_SUPER_SIMPLIFICATION" NUMBER(2, 0) NOT NULL ENABLE,
	"KUND_NUMBER_OF_ADMISSION" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"KUND_GB_SUB_LINE" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"KUND_DOC_HANDLING" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"KUND_DOCUMENT_HANDLING_BY" VARCHAR2(17 CHAR) NOT NULL ENABLE,
	"KUND_DOCUMENT_TRANSPORT" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_SECURITY_STATEMENT" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_SECUR_STAT_VALID_UNTIL_1" NUMBER(10, 0) NOT NULL ENABLE,
	"KUND_TRANSPORT_OF_VALUABLES" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"KUND_SELF_COLLECTION" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_COLLECT_CC_FEES_IN_CASH" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_CREDIT_CC_FEES" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_CASS_BILLING_PP" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_IMA_INVOICE_NUMBER_CC" NUMBER(6, 0) NOT NULL ENABLE,
	"KUND_CC_ADMINISTRATION_FEES" NUMBER(2, 0) NOT NULL ENABLE,
	"KUND_CC_ADM_FEES_MINIMUM" NUMBER(5, 2) NOT NULL ENABLE,
	"KUND_CC_ADM_FEES_MAXIMIUM" NUMBER(5, 2) NOT NULL ENABLE,
	"KUND_NIL_MANIFEST" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_DISPATCH_CONTRACT" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_DISP_CONTR_VALID_FROM" NUMBER(10, 0) NOT NULL ENABLE,
	"KUND_CONTRACT_NO_" VARCHAR2(12 CHAR) NOT NULL ENABLE,
	"KUND_SUPER_CUMULATION_CUST_" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_SOKO" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_SEPARATE_INVOICING" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_GOODS_ADDRESS" NUMBER(6, 0) NOT NULL ENABLE,
	"KUND_BANK_DEBIT_MEMO" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_BANK_CODE" VARCHAR2(8 CHAR) NOT NULL ENABLE,
	"KUND_ACCOUNT" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	"KUND_GRACE_PERIOD" NUMBER(3, 0) NOT NULL ENABLE,
	"KUND_FWB_FORWARD" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_FOREIGN_SYSTEM" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"KUND_FLIGHT_SCHEDULE_TRANSFER" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"KUND_CHECK_TIMES_EVALUATION" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_SITA_DOUBLE_SIGNATURE" VARCHAR2(5 CHAR) NOT NULL ENABLE,
	"KUND_PRINTING_LOCATION" NUMBER(4, 0) NOT NULL ENABLE,
	"KUND_FFM_DENSITY_GROUP" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_RECORD_DELETED" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_FILLER" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_DATA_TRANSFER" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_LABEL_PRINT_F_EXPORT" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_INVOICES_ISSUING" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"KUND_CUSTOMS_SHIPMENT" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_WAY_BILL_ISSUING" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_DG_CHECK" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_CONTRACT_REMARK" RAW(182) NOT NULL ENABLE,
	"KUND_REMARK" RAW(182) NOT NULL ENABLE,
	"KUND_SECUR_STAT_VALID_UNTIL_2" NUMBER(10, 0) NOT NULL ENABLE,
	"KUND_IMA_INVOIVE_NUMBER_PP" NUMBER(6, 0) NOT NULL ENABLE,
	"KUND_CHEQUE_DAILY" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_CHEQUE_WEEKLY" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_TRANSFER_DAILY" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_TRANSFER_WEEKLY" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_CREDIT_MONTHLY" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_INVOINCING_TO_CARRIER" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_CHARGE_THROUGH_CASS" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_DOC_HANDLING_INCLUSIVE" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_DATA_MEDIUM_REPLACEMENT" NUMBER(1, 0) NOT NULL ENABLE,
	"KUND_LANGUAGE_CODE" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"UNKNOWN" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_PRICE_LIST" VARCHAR2(50 CHAR),
	"CUSTOMS_CODE" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"IMPORT_CUSTOMER" NUMBER(1, 0) NOT NULL ENABLE,
	"EXPORT_CUSTOMER" NUMBER(1, 0) NOT NULL ENABLE,
	"ABLE_TO_MOVE_TO_BOND" NUMBER(1, 0) NOT NULL ENABLE,
	"STANDING_INSTRUCTIONS" VARCHAR2(4000 CHAR) NOT NULL ENABLE,
	"DISPLAY_STANDING_INSTRUCTIONS" NUMBER(1, 0) NOT NULL ENABLE,
	"INCA_ACCOUNT_CODE" VARCHAR2(12 CHAR) NOT NULL ENABLE,
	"KUND_SUN_ACCOUNT_CODE" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"KUND_SUN_ACCOUNT_AL_CODE" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"KUND_CC_FEE_AL" NUMBER(1, 0) DEFAULT 0,
	"KUND_CC_FEE_DATE" DATE,
	"KUND_CFS_BOARD_NUMBER" NUMBER(1, 0),
	"KUND_AIRLINE_DO_NOT_INVOICE" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_AIRPORT" VARCHAR2(5 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_TSHPMNT_DFLT_MANIFEST" NUMBER(2, 0) DEFAULT 2 NOT NULL ENABLE,
	"KUND_AIRLINE_TARIFF" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_DOCS_SHOULD_ARRIVE" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"KUND_MUST_CAPTURE_FWB" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_CAN_RECEIVE_MULTIPLE_FFM" NUMBER(1, 0) DEFAULT 1 NOT NULL ENABLE,
	"KUND_GWE_PERCENTAGE_EXCESS" NUMBER(3, 0) DEFAULT 10 NOT NULL ENABLE,
	"KUND_CUST_PRINTER_QUEUE" VARCHAR2(255 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_VOLUME_DISCREPANCY" NUMBER(3, 0) DEFAULT 10 NOT NULL ENABLE,
	"KUND_FSL_STATUS" VARCHAR2(50 CHAR),
	"KUND_FSL_TIME" VARCHAR2(6 CHAR),
	"KUND_WEIGHT_IN_FSU" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_CUSTOMS_ID" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CUSTOMS_PRE_CLEARANCE" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_CUSTOMS_CLEARANCE_REMARK" VARCHAR2(255 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CASH_REASON" VARCHAR2(180 CHAR),
	"KUND_RECALCULATE_FLAG" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CC_PP_AIRLINE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_DEFAULT_EXPIRE_DATE" DATE,
	"KUND_DEFAULT_PAYMENT_TYPE" VARCHAR2(50 CHAR) DEFAULT NULL,
	"KUND_DEFAULT_CARD_NO" VARCHAR2(50 CHAR) DEFAULT NULL,
	"KUND_FFM_VOLUME" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_METER_CUBIC" NUMBER(18, 6) DEFAULT 0 NOT NULL ENABLE,
	"KUND_ACCOUNT_HANDLING_TYPE" VARCHAR2(50 CHAR) DEFAULT 'TSO' NOT NULL ENABLE,
	"KUND_GWE_AWB_UPTO_WEIGHT" NUMBER(8, 1) DEFAULT 0 NOT NULL ENABLE,
	"KUND_GWE_AWB_WEIGHT" NUMBER(8, 1) DEFAULT 0 NOT NULL ENABLE,
	"KUND_GWE_ULD_PERCENTAGE_EXCESS" NUMBER(3, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_GWE_ULD_UPTO_WEIGHT" NUMBER(8, 1) DEFAULT 0 NOT NULL ENABLE,
	"KUND_GWE_ULD_WEIGHT" NUMBER(8, 1) DEFAULT 0 NOT NULL ENABLE,
	"KUND_TEMPLATE_PATH" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_AWB_PRINT_NO_PRICES" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_HAWB_REQUIREMENT" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CONTRACT_IMPORT" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CONTRACT_EXPORT" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_GWE_DEVIATION_TYPE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_AWB_PRINT_NO_PRC_AOD" VARCHAR2(1000 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_ULD_NAMING_CONVENTION" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_ACCOUNT_TYPE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CREDIT_LIMIT" NUMBER(8, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_ULD_HANDLING_METHOD" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_ULD_HANDLING_WAREHOUSE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CUSTOMS_WITHOUT_CONFIRM" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_CONTRACT_IMP_DOMESTIC" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CONTRACT_EXP_DOMESTIC" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_MANDATORY_BOOKED_VOLUME" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_FWB_FHL_SEND_MESSAGE_BY" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_LOADPLAN_SHCS" VARCHAR2(255 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_PREFIX_START_DATE" DATE,
	"KUND_PREFIX_END_DATE" DATE,
	"KUND_AUTOMATIC_ADVICE" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_DOCUMENTS_BOX" VARCHAR2(50 CHAR) DEFAULT ' ',
	"KUND_SHORTCODE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CONTINUE_FLIGHT_REQUIRED" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_CUSTOMS_BY_CUSTOMER" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_LIVE_AWB_INTERVAL" NUMBER(3, 0) DEFAULT 180 NOT NULL ENABLE,
	"KUND_OVERRIDE_VAT" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_VAT_ALWAYS_OVERRIDE" NUMBER(2, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_SIMPLIFIED_PROCEDURE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_FFM_ULD_MOVEMENT_INFO" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CARGO2000" VARCHAR2(50 CHAR) DEFAULT ' ',
	"KUND_CREDIT_DAYS" NUMBER(4, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_AL_CONTRACT_TYPE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_AL_NOTOC_OTHER_SHC" VARCHAR2(255 CHAR),
	"KUND_FBL_UPDATE_MODE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_EXPORT_TRANSIT_FSU_TYPE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_INTERNAL_IDENT" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_MARK_AUTO_DELIVERY" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_DETR_CODE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CUSTOMER_CHARGES_ISN" NUMBER(14, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_SECURE_SHIPMENT" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_ALLOW_WORK_WITH_COPY" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_INVOICE_REF" VARCHAR2(500 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_ALLOW_NOA" NUMBER(1, 0),
	"KUND_PRE_PAY_BALANCE" NUMBER(18, 6) DEFAULT 0 NOT NULL ENABLE,
	"KUND_PRE_PAY_MINIMUM" NUMBER(18, 6) DEFAULT 0 NOT NULL ENABLE,
	"KUND_CHARGES_SCREEN_MESSAGE" VARCHAR2(255 CHAR),
	"KUND_CHARGES_SCR_MSG_ALL_OBJ" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_IE_CODE_MANDATORY" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_PICKUP_MSG_TIME_ULD" NUMBER(4, 0) DEFAULT 60 NOT NULL ENABLE,
	"KUND_PICKUP_MSG_TIME_LOOSE" NUMBER(4, 0) DEFAULT 60 NOT NULL ENABLE,
	"KUND_AGENT_HANDLE_ULD" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_RCS_TRIGGER" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CUSTOMER_PAYMENT_INFO" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_MAIL_HANDLING_TYPE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_ICS_PROCESS" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_EORI_NUMBER" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_EXPORT_MAIL_HANDLING" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_IMPORT_MAIL_HANDLING" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_AUTO_EXPORT_MAIL_SHC" VARCHAR2(3 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_AUTO_IMPORT_MAIL_SHC" VARCHAR2(3 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CUSTOMER_SUBTYPE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_WARN_WEIGHT_DEVIATION" NUMBER(1, 0),
	"KUND_WAITING_TIME" NUMBER(3, 0) DEFAULT 0,
	"KUND_NOTOC_SORT_PACKAGE" NUMBER(1, 0),
	"KUND_AIRLINE_LAT" NUMBER(3, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_AIRLINE_EXPRESS_LAT" NUMBER(3, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_SIMPLIFIEDPROC_NO" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_SIMPLIFIEDPROC_DATE" DATE,
	"KUND_SIMPLIFIEDPROC_OFFICE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_ICS_AUTOMATIC_TRIGGER" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_DECIMAL_DIGITS_IN_FFM" NUMBER(3, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_CUSTOMER_INVOICE_CURRENCY" VARCHAR2(3) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_CUSTOMER_INVOICE_SUBTYPE" VARCHAR2(50) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_DEFAULT_MANAGING_AIRLINE" VARCHAR2(3) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_SHOW_PRICES_AWB_AS_AGREED" NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
	"KUND_NOTOC_SORT_OPTION" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_STOCK_AWB_EMAIL_LOW_LIMIT" NUMBER(3, 0) DEFAULT '0' NOT NULL ENABLE,
	"KUND_STOCK_AWB_EMAIL_ADDRESS" VARCHAR2(500 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_RAMP_LOCATION_TYPE" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_RAMP_FLIGHT_TYPES" VARCHAR2(500 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_EORI_BRANCH" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_MAIL_ON_CARGO_MANIFEST" NUMBER(1, 0) DEFAULT '0' NOT NULL ENABLE,
	"KUND_EAWB_FORWARDING_STATUS" VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ENABLE,
	"KUND_MANIFEST_FFM_BY_EXPECTED" NUMBER(1, 0) DEFAULT '1' NOT NULL ENABLE,
	"KUND_MANI_FFM_BY_XPCT_INTC_ULD" NUMBER(1, 0) DEFAULT '0' NOT NULL ENABLE,
	CONSTRAINT "KUND_CUSTOMER_ZERO" CHECK (KUND_CUSTOMER_NO_ <> 0) ENABLE
);

GRANT SELECT ON "LIM_W1_HL"."KUND" TO CDC_USER;

ALTER TABLE "LIM_W1_HL"."KUND"
	ADD SUPPLEMENTAL LOG DATA (
		ALL
	) COLUMNS;

CREATE INDEX "LIM_W1_HL"."BY_3_LETTER_CODE_AND_AIRPORT" ON "LIM_W1_HL"."KUND" ("KUND_CUSTOMER_TYPE_CODE", "KUND_3_LETTER_CODE", "KUND_AIRPORT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."IDX_KUND" ON "LIM_W1_HL"."KUND" ("KUND_CUSTOMER_TYPE_CODE", "KUND_3_LETTER_CODE", "KUND_RECORD_DELETED")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE UNIQUE INDEX "LIM_W1_HL"."KEY001KUND" ON "LIM_W1_HL"."KUND" ("KUND_CUSTOMER_NO_")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KEY002KUND" ON "LIM_W1_HL"."KUND" ("KUND_OLD_CUSTOMER_NO_")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KEY003KUND" ON "LIM_W1_HL"."KUND" ("KUND_NAME_1")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KEY004KUND" ON "LIM_W1_HL"."KUND" ("KUND_LVG")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KEY005KUND" ON "LIM_W1_HL"."KUND" ("KUND_2_LETTER_CODE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KEY006KUND" ON "LIM_W1_HL"."KUND" ("KUND_PREFIX")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KEY007KUND" ON "LIM_W1_HL"."KUND" ("KUND_3_LETTER_CODE", "KUND_2_LETTER_CODE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KEY008KUND" ON "LIM_W1_HL"."KUND" ("KUND_IATA_CA_NUMERICAL_CODE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KEY009KUND" ON "LIM_W1_HL"."KUND" ("KUND_CUSTOMER_TYPE_CODE", "KUND_NAME_1")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KEY010KUND" ON "LIM_W1_HL"."KUND" ("KUND_CUSTOMS_NUMBER")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KUND_BY_ADDRESS" ON "LIM_W1_HL"."KUND" ("KUND_STREET_1")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KUND_BY_CITY" ON "LIM_W1_HL"."KUND" ("KUND_CITY")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KUND_BY_SHORT_CODE" ON "LIM_W1_HL"."KUND" ("KUND_SHORTCODE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KUND_BY_TYPE_3_LETTER_CODE" ON "LIM_W1_HL"."KUND" ("KUND_CUSTOMER_TYPE_CODE", "KUND_3_LETTER_CODE", "KUND_CUSTOMER_NO_")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE INDEX "LIM_W1_HL"."KUND_CUSTOMS" ON "LIM_W1_HL"."KUND" ("KUND_RECORD_DELETED", "KUND_CUSTOMER_TYPE_CODE", "KUND_CUSTOMS_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE UNIQUE INDEX "LIM_W1_HL"."KUND_EORI" ON "LIM_W1_HL"."KUND" ("KUND_EORI_NUMBER", "KUND_CUSTOMER_TYPE_CODE", "KUND_RECORD_DELETED", "KUND_CUSTOMER_NO_")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE UNIQUE INDEX "LIM_W1_HL"."KUND_I01" ON "LIM_W1_HL"."KUND" ("KUND_RECORD_DELETED", "KUND_CUSTOMER_TYPE_CODE", "KUND_3_LETTER_CODE", "KUND_2_LETTER_CODE", "KUND_CUSTOMER_NO_")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE UNIQUE INDEX "LIM_W1_HL"."KUND_I02" ON "LIM_W1_HL"."KUND" ("KUND_3_LETTER_CODE", "KUND_RECORD_DELETED", "KUND_2_LETTER_CODE", "KUND_CUSTOMER_NO_")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);