services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    restart: always
    env_file:
      - ./env/deploy.env
    networks:
      - integration-network
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/var/lib/kafka/data
      - ./config/prometheus/prometheus.template.yml:/etc/prometheus/prometheus.template.yml
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "$(cat /etc/prometheus/prometheus.template.yml)" | \
        tr '$' '@' | \
        sed "s/@{CONTROLLER_1_IP}/$CONTROLLER_1_IP/g" | \
        sed "s/@{CONTROLLER_2_IP}/$CONTROLLER_2_IP/g" | \
        sed "s/@{BROKER_1_IP}/$BROKER_1_IP/g" | \
        sed "s/@{BROKER_2_IP}/$BROKER_2_IP/g" | \
        sed "s/@{SOURCE_CONNECT_IP}/$SOURCE_CONNECT_IP/g" | \
        sed "s/@{SINK_CONNECT_IP}/$SINK_CONNECT_IP/g" > /etc/prometheus/prometheus.yml && \
        /bin/prometheus \
          --config.file=/etc/prometheus/prometheus.yml \
          --storage.tsdb.path=/prometheus \
          --web.console.libraries=/usr/share/prometheus/console_libraries \
          --web.console.templates=/usr/share/prometheus/consoles

# networks:
#   integration-network:
#     name: integration-network
#     driver: bridge

networks:
  integration-network:
    external: true

volumes:
  prometheus_data:
