# prometheus/prometheus.yml

global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files: ["rules/*.yml"]

alerting:
  alertmanagers:
    - timeout: "10s"
      scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "kafka-controllers"
    static_configs:
      - targets:
          - "controller-1:9200"
          - "controller-2:9200"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):(.*)"
      - target_label: node_type
        replacement: "controller"

  - job_name: "kafka-brokers"
    static_configs:
      - targets:
          - "broker-1:9200"
          - "broker-2:9200"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):(.*)"
      - target_label: node_type
        replacement: "broker"

  - job_name: "kafka-connects"
    static_configs:
      - targets:
          - "connect:9200"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):(.*)"
      - target_label: node_type
        replacement: "connect"

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "host.docker.internal:9100"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):(.*)"
      - target_label: node_type
        replacement: "host"
